require 'rake'
require 'rspec/core/rake_task'

task :spec    => 'spec:all'
task :default => :spec

namespace :spec do
  targets = []
  Dir.glob('./spec/*').each do |dir|
    next unless File.directory?(dir)
    targets << File.basename(dir)
  end

  task :all     => targets.map{|target| target + '-all'}
  task :default => :all

  targets.each do |target|
    desc "Run all serverspec tests against #{target}"
    RSpec::Core::RakeTask.new((target + '-all').to_sym, :ip) do |t, args|
      ENV['TARGET_HOST'] = target
      t.pattern = "spec/#{target}/**/*_spec.rb"

      ip = args[:ip]
      if ip.nil?
        ip = '10.1.2.2'
      end
      ENV['TARGET_IP'] = ip
      puts "Target Host: #{ENV['TARGET_HOST']}"
      puts "Target IP: #{ENV['TARGET_IP']} "
    end
  end

  targets.each do |target|
    desc "Run all smoke serverspec tests against #{target}"
    RSpec::Core::RakeTask.new((target + '-smoke').to_sym, :ip) do |t, args|
      ENV['TARGET_HOST'] = target
      t.pattern = "spec/#{target}/smoke/*_spec.rb"

      ip = args[:ip]
      if ip.nil?
        ip = '10.1.2.2'
      end
      ENV['TARGET_IP'] = ip
      puts "Target Host: #{ENV['TARGET_HOST']}"
      puts "Target IP: #{ENV['TARGET_IP']}"
    end
  end

  targets.each do |target|
    Dir.glob("spec/#{target}/**/*_spec.rb").each do |spec|
      spec_name = File.basename(spec).chomp('_spec.rb')
      desc "Run single spec #{spec_name} against #{target}"
      RSpec::Core::RakeTask.new((target + '-' + spec_name).to_sym, :ip) do |t, args|
        ENV['TARGET_HOST'] = target
        t.pattern = spec

        ip = args[:ip]
        if ip.nil?
          ip = '10.1.2.2'
        end
        ENV['TARGET_IP'] = ip
        puts "Target Host: #{ENV['TARGET_HOST']}"
        puts "Target IP: #{ENV['TARGET_IP']}"
      end
    end
  end
end
