# -*- mode: ruby -*-
# vi: set ft=ruby :

# Usage:
#
# To use this Vagrantfile, you(optional):
# * Connected to internal Red Hat network if you need to any package update
# * Have 'vagrant-registration' plugin installed
# * Have valid RH employee subscription account
# * Have 'vagrant-adbinfo' plugin installed

# General configuration:

# URLs from where to fetch the Vagrant Virtualbox images
# FIXME: How to point to the official box image?
VAGRANT_BOX_BASE="http://10.3.10.216/builds/11-Dec-2015"
VAGRANT_VIRTUALBOX_URL="#{VAGRANT_BOX_BASE}/rhel-7.2-server-kubernetes-vagrant-scratch-7.2-1.x86_64.vagrant-virtualbox.box"
VAGRANT_LIBVIRT_URL="#{VAGRANT_BOX_BASE}/rhel-7.2-server-kubernetes-vagrant-scratch-7.2-1.x86_64.vagrant-libvirt.box"

# The public IP address of the VM
PUBLIC_ADDRESS="10.1.2.2"

# The public hostname for the box. Uses xip.io to have zero configuration routes
PUBLIC_HOST="cdk.#{PUBLIC_ADDRESS}.xip.io"

SUBSCRIPTION_INFO = "
    Red Hat subscription credentials are needed for this VM.
    You can supply them interactively or by setting environment variables.
    Set these environment variables to your subscription username/password to avoid interactive registration:

    $ export SUB_USERNAME=rhn-username
    $ export SUB_PASSWORD=password
  "

NO_ADBINFO_ERROR = "vagrant-adbinfo plugin is not installed, run `vagrant plugin install vagrant-adbinfo` to install the plugin."
NO_VAGRANT_REGISTRATION_ERROR = "vagrant-registration plugin is not installed, run `vagrant plugin install vagrant-registration` to install the plugin."

Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |v, override|
  	override.vm.box = "cdk_v2"
    override.vm.box_url = "#{VAGRANT_VIRTUALBOX_URL}"
    v.name = "openshift.cdk-2"
    v.memory = 1024
    v.cpus   = 2
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.provider "libvirt" do |v, override|
  	override.vm.box = "cdk_v2"
    override.vm.box_url = "#{VAGRANT_LIBVIRT_URL}"
    v.driver = "kvm"
    v.memory = 1024
    v.cpus   = 2
  end

  config.vm.network "private_network", ip: "#{PUBLIC_ADDRESS}"

  unless Vagrant.has_plugin?("vagrant-adbinfo")
    raise Vagrant::Errors::VagrantError.new, NO_ADBINFO_ERROR
  end

  unless Vagrant.has_plugin?('vagrant-registration')
    raise Vagrant::Errors::VagrantError.new, NO_VAGRANT_REGISTRATION_ERROR
  end

  config.registration.username    = ENV.has_key?('SUB_USERNAME') ? "#{ENV['SUB_USERNAME']}" : nil
  config.registration.password    = ENV.has_key?('SUB_PASSWORD') ? "#{ENV['SUB_PASSWORD']}" : nil
  config.registration.auto_attach = true

  case ARGV[0]
  when "up", "halt"
    if config.registration.username.nil? || config.registration.password.nil?
      puts SUBSCRIPTION_INFO
    end
  end

  config.vm.provision :shell, :path => "./scripts/configure_docker.sh"
  config.vm.provision :shell, :path => "./scripts/configure_ose.sh", :args => "#{PUBLIC_ADDRESS} #{PUBLIC_HOST}"

  config.vm.provision "shell", inline: <<-SHELL
    echo
    echo "You can now access OpenShift console on: https://#{PUBLIC_ADDRESS}:8443/console"
    echo
    echo "To use OpenShift CLI, run:"
    echo "$ vagrant ssh"
    echo "$ oc status"
    echo
    echo "To become a cluster-admin, add '--config' to oc commands:"
    echo "$ vagrant ssh"
    echo "$ oc status --config=/var/lib/origin/openshift.local.config/master/admin.kubeconfig"
    echo
  SHELL

end

